postgres:
  host: localhost
  port: 5432
  user: restaurant_user
  password: restaurant_pass
  database: restaurant_db

rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest

  order:
    exchange: "orders_topic"

  notifications:
    exchange: "notifications_fanout"
  
  reconnect:
    attempt: 5
    delay: 2s


order:
  semwait: 1s

kitchen:
  reconnect:
    attempt: 5
    delay: 2s
